---
- name: My first playbook :)
  hosts: "webservers"
  become: true
  become_user: root
  tasks:
  roles:
    - { role: geerlingguy.mysql,2.3.1}
    - { role: geerlingguy.apache,1.7.2}
    - { role: copy}
    